In [19]:
"""
-----------------------------------------------------------------------------
Assignment-1: Matrix computation exercise using python and numpy
-----------------------------------------------------------------------------
AUTHOR: Soumitra Samanta (soumitra.samanta@gm.rkmvu.ac.in)
-----------------------------------------------------------------------------
Package required:
Numpy: https://numpy.org/
Matplotlib: https://matplotlib.org
-----------------------------------------------------------------------------
"""

import numpy as np
import random
from numpy.random import RandomState

from typing import Tuple

np.random.seed(42)# To reproduce the random numbers



# Generate a random vector $x \in \mathbf{R}^{n}$ contains intergers between $[-l, l]$.
[3 points]

In [20]:
n = 10
l = 9
x=[]
############################################################################
#                             Your code will be here                       #
#--------------------------------------------------------------------------#
x = [random.randint(-l, l) for _ in range(n)]
#--------------------------------------------------------------------------#
#                             End of your code                             #
############################################################################

print('A random vector of size {}: ' .format(n))
print('-'*70)
print('x:{} ' .format(x))
print('-'*70)

A random vector of size 10: 
----------------------------------------------------------------------
x:[-9, -2, -9, 0, 4, -2, -7, -8, 0, -5] 
----------------------------------------------------------------------


# Write a function to calculate the 'dot' product between two vectors. Generate two random vectors $x, y \in \mathbf{R}^{n}$ contains intergers between $[-l, l]$ and find the dot product between $x$ and $y$ (your function should handle different order vectors). Check your result with the [numpy.dot](https://numpy.org/doc/stable/reference/generated/numpy.dot.html).
[5 points]




In [21]:
n = 10
l = 9
x = []
y = []

def vector_dot_product(
    x: np.array,
    y: np.array,
)->float:
    """
    Dot product between two vectors
    
    Inputs:
        - x: 1st vector
        - y: 2nd vector
       
    Output:
        - val: Dot product between x and y
    
    """
    
    val = []
    ############################################################################
    #                             Your code will be here                       #
    #--------------------------------------------------------------------------#
  
    # x = [random.randint(-l, l) for _ in range(n)]
    # y = [random.randint(-l, l) for _ in range(n)]
    sum=0
    for i in range(len(x)):
        sum+=x[i] * y[i]
    val.append(sum)

    #--------------------------------------------------------------------------#
    #                             End of your code                             #
    ############################################################################
    
    return val

# np.random.seed(42)# for reproduce the random numbers
x = []
y = []
x = [random.randint(-l, l) for _ in range(n)]
y = [random.randint(-l, l) for _ in range(n)]

print('Two random vectors of size {} are:' .format(n))
print('-'*70)
print('x: {}\nand \ny: {}' .format(x, y))
print('-'*70)

val = vector_dot_product(x, y)
print('The dot product between x and y is: {}' .format(val))
dot_product=np.dot(x,y)
if val[0]==dot_product:
        print("dot product is valid ")
print('-'*70)

Two random vectors of size 10 are:
----------------------------------------------------------------------
x: [-8, -7, 9, 8, -3, 0, 3, 8, 5, 1]
and 
y: [9, -9, -2, 8, -3, 6, -4, -7, 2, -2]
----------------------------------------------------------------------
The dot product between x and y is: [-14]
dot product is valid 
----------------------------------------------------------------------


# Generate a random matrix $A$ of size $m \times n$ contains intergers between $[-l, l]$.
[2 points]

In [22]:
m = 3
n = 5
l = 9
A = []
############################################################################
#                             Your code will be here                       #
#--------------------------------------------------------------------------#
A = np.array([[random.randint(-l, l) for _ in range(n)] for _ in range(m)])

#--------------------------------------------------------------------------#
#                             End of your code                             #
############################################################################

print('A random matrix of size {}x{} A:\n{}: ' .format(m, n, A))
print('-'*70)



A random matrix of size 3x5 A:
[[ 1  1  9  8 -2]
 [ 3 -9  4 -8 -6]
 [-4  8 -9  0  8]]: 
----------------------------------------------------------------------


# Write a function to calculate the product of two matrices. Generate two random matrices $x \in \mathbf{R}^{m \times n}$ and $y \in \mathbf{R}^{n \times m}$ contains intergers between $[-l, l]$ and find the product of of $x$ and $y$ (your function should handle different order matrices). Check your result with the [numpy.matmul](https://numpy.org/doc/stable/reference/generated/numpy.matmul.html) or [numpy.dot](https://numpy.org/doc/stable/reference/generated/numpy.dot.html).

[10 points]




In [23]:
m = 3
n = 5
l = 9
x = []
y = []

def matrix_multiplication(
    x: np.array,
    y: np.array,
)->np.array:
    """
    Dot product between two vectors
    
    Inputs:
        - x: 1st matrix
        - y: 2nd matrix
       
    Output:
        - val: multiplication x and y
    
    """
    
    val = []
    ############################################################################
    #                             Your code will be here                       #
    #--------------------------------------------------------------------------#
    
    if len(x) != len(y[0]):
        raise ValueError("Number of columns in the first matrix must equal the number of rows in the second matrix")        
    m = len(x)
    n = len(y[0])
    val = [[0 for _ in range(n)] for _ in range(m)]
    for i in range(m):
        for j in range(n):
            for k in range(len(y)):
                val[i][j] += x[i][k] * y[k][j]
        

            
    #--------------------------------------------------------------------------#
    #                             End of your code                             #
    ############################################################################
    
    return val

# np.random.seed(42)# for reproduce the random numbers
A=[]
B=[]
A=np.array([[random.randint(-l, l) for _ in range(n)] for _ in range(m)])
B=np.array([[random.randint(-l, l) for _ in range(m)] for _ in range(n)])

print('Two random matrices are:')
print('A: \n{}\nand\nB: \n{}' .format(A, B))
print('-'*70)

val = np. array(matrix_multiplication(A, B))
print('The multiplication of A and B using my function is: \n{}' .format(val))
print('-'*70)

val1 = np.matmul(A, B)
print('The multiplication of A and B using numpy.matmul is: \n{}' .format(val1))
print('-'*70)

val1 = np.dot(A, B)
print('The multiplication of A and B using numpy.dot is: \n{}' .format(val1))
print('-'*70)


Two random matrices are:
A: 
[[-5  3  5  9  5]
 [ 8 -2 -5  2  1]
 [ 0  0  7 -3  9]]
and
B: 
[[-3 -3 -7]
 [ 3  3 -1]
 [-3 -9 -2]
 [ 7 -7 -2]
 [-6 -3 -1]]
----------------------------------------------------------------------
The multiplication of A and B using my function is: 
[[ 42 -99  -1]
 [ -7  -2 -49]
 [-96 -69 -17]]
----------------------------------------------------------------------
The multiplication of A and B using numpy.matmul is: 
[[ 42 -99  -1]
 [ -7  -2 -49]
 [-96 -69 -17]]
----------------------------------------------------------------------
The multiplication of A and B using numpy.dot is: 
[[ 42 -99  -1]
 [ -7  -2 -49]
 [-96 -69 -17]]
----------------------------------------------------------------------
